Falha ao corrigir.

Testes falharam

Log

FAILED python_testcases/test_hanoi.py::test_hanoi[input_data1-expected1] - assert [(1, 2)] == [(1, 3)]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data2-expected2] - assert [(1, 3), (1, 2), (2, 1)] == [(1, 2), (1, 3), (2, 3)]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data3-expected3] - assert [(1, 2), (1, ..., (2, 1), ...] == [(1, 3), (1, ..., (2, 3), ...]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data4-expected4] - assert [(1, 3), (1, ..., (3, 1), ...] == [(1, 2), (1, ..., (3, 2), ...]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data5-expected5] - assert [(1, 2), (1, 3), (3, 1)] == [(1, 3), (1, 2), (3, 2)]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data6-expected6] - assert [(1, 3), (1, 2), (2, 3)] == [(1, 2), (1, 1), (2, 1)]
FAILED python_testcases/test_hanoi.py::test_hanoi[input_data7-expected7] - assert [(3, 1), (3, 2), (2, 3)] == [(3, 2), (3, 1), (2, 1)]
