Falha na correção

Testes Falharam

tenta resolver qualquer outra coisa

LOG

================================================== FAILURES ==================================================
_______________________________________ test_knapsack[input_data0-19] ________________________________________

input_data = [100, [[60, 10], [50, 8], [20, 4], [20, 4], [8, 3], [3, 2]]], expected = 19

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 100, items = [[60, 10], [50, 8], [20, 4], [20, 4], [8, 3], [3, 2]]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data1-30] ________________________________________

input_data = [40, [[30, 10], [50, 5], [10, 20], [40, 25]]], expected = 30

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 40, items = [[30, 10], [50, 5], [10, 20], [40, 25]]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
______________________________________ test_knapsack[input_data2-1458] _______________________________________

input_data = [750, [[70, 135], [73, 139], [77, 149], [80, 150], [82, 156], [87, 163], ...]], expected = 1458

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 750, items = [[70, 135], [73, 139], [77, 149], [80, 150], [82, 156], [87, 163], ...]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data3-51] ________________________________________

input_data = [26, [[12, 24], [7, 13], [11, 23], [8, 15], [9, 16]]], expected = 51

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 26, items = [[12, 24], [7, 13], [11, 23], [8, 15], [9, 16]]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data4-107] _______________________________________

input_data = [50, [[31, 70], [10, 20], [20, 39], [19, 37], [4, 7], [3, 5], ...]], expected = 107

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 50, items = [[31, 70], [10, 20], [20, 39], [19, 37], [4, 7], [3, 5], ...]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data5-150] _______________________________________

input_data = [190, [[56, 50], [59, 50], [80, 64], [64, 46], [75, 50], [17, 5]]], expected = 150

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 190, items = [[56, 50], [59, 50], [80, 64], [64, 46], [75, 50], [17, 5]]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data6-900] _______________________________________

input_data = [104, [[25, 350], [35, 400], [45, 450], [5, 20], [25, 70], [3, 8], ...]], expected = 900

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 104, items = [[25, 350], [35, 400], [45, 450], [5, 20], [25, 70], [3, 8], ...]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
_______________________________________ test_knapsack[input_data7-309] _______________________________________

input_data = [165, [[23, 92], [31, 57], [29, 49], [44, 68], [53, 60], [38, 43], ...]], expected = 309

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 165, items = [[23, 92], [31, 57], [29, 49], [44, 68], [53, 60], [38, 43], ...]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
______________________________________ test_knapsack[input_data8-1735] _______________________________________

input_data = [170, [[41, 442], [50, 525], [49, 511], [59, 593], [55, 546], [57, 564], ...]], expected = 1735

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_knapsack(input_data, expected):
        if not pytest.run_slow and input_data == [
            6404180,
            [
                [382745, 825594],
                [799601, 1677009],
                [909247, 1676628],
                [729069, 1523970],
                [467902, 943972],
                [44328, 97426],
                [34610, 69666],
                [698150, 1296457],
                [823460, 1679693],
                [903959, 1902996],
                [853665, 1844992],
                [551830, 1049289],
                [610856, 1252836],
                [670702, 1319836],
                [488960, 953277],
                [951111, 2067538],
                [323046, 675367],
                [446298, 853655],
                [931161, 1826027],
                [31385, 65731],
                [496951, 901489],
                [264724, 577243],
                [224916, 466257],
                [169684, 369261],
            ],
        ]:
            pytest.skip("Takes about 4 mins to pass!")
>       assert knapsack(*input_data) == expected

python_testcases/test_knapsack.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

capacity = 170, items = [[41, 442], [50, 525], [49, 511], [59, 593], [55, 546], [57, 564], ...]

    def knapsack(capacity, items):
        from collections import defaultdict
        memo = defaultdict(int)

        # Base case: knapsack with 0 capacity has 0 value
        for j in range(capacity + 1):
            memo[0, j] = 0

        for i in range(1, len(items) + 1):
>           weight, value = items[i]
E           IndexError: list index out of range

python_programs/knapsack.py:10: IndexError
========================================== short test summary info ===========================================
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data0-19] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data1-30] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data2-1458] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data3-51] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data4-107] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data5-150] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data6-900] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data7-309] - IndexError: list index out of range
FAILED python_testcases/test_knapsack.py::test_knapsack[input_data8-1735] - IndexError: list index out of rang
